server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/music
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        dbcp2:
            initial-size: 5
            min-idle: 10
            max-idle: 20
        tomcat:
            max-active: 20
    jpa:
        database: MYSQL
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            format_sql: true
