server:
    port: 8088
resURL: http://localhost:8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/music
        username: root
        password: root
        initialSize: 5
        minIdle: 10
        maxIdle: 20
        maxActive: 20
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            format_sql: true
